from config.env import env_bool, env_float, env_int, get_env_variable

WHISPER_MODEL: str = get_env_variable(
    "WHISPER_MODEL", "Systran/faster-distil-whisper-large-v3"
)

WHISPER_PARTIAL_BEAM: int = env_int("WHISPER_PARTIAL_BEAM", "1")
WHISPER_FINAL_BEAM: int = env_int("WHISPER_FINAL_BEAM", "2")
WHISPER_PARTIAL_CONDITION_PREVIOUS: bool = env_bool("WHISPER_PARTIAL_CONDITION_PREVIOUS", "false")
WHISPER_FINAL_CONDITION_PREVIOUS: bool = env_bool("WHISPER_FINAL_CONDITION_PREVIOUS", "true")
WHISPER_WITHOUT_TIMESTAMPS: bool = env_bool("WHISPER_WITHOUT_TIMESTAMPS", "true")

SEGMENT_MIN_AVG_LOGPROB_PARTIAL: float = env_float("SEGMENT_MIN_AVG_LOGPROB_PARTIAL", "-0.9")
SEGMENT_MIN_AVG_LOGPROB_FINAL: float = env_float("SEGMENT_MIN_AVG_LOGPROB_FINAL", "-1.12")
SEGMENT_MAX_NO_SPEECH_PROB_PARTIAL: float = env_float("SEGMENT_MAX_NO_SPEECH_PROB_PARTIAL", "0.65")
SEGMENT_MAX_NO_SPEECH_PROB_FINAL: float = env_float("SEGMENT_MAX_NO_SPEECH_PROB_FINAL", "0.82")

TRANSCRIBE_MIN_RMS: float = env_float("TRANSCRIBE_MIN_RMS", "0.004")

WHISPER_NO_SPEECH_THRESHOLD: float = env_float("WHISPER_NO_SPEECH_THRESHOLD", "0.95")
WHISPER_LOG_PROB_THRESHOLD: float = env_float("WHISPER_LOG_PROB_THRESHOLD", "-1.0")
WHISPER_COMPRESSION_RATIO_THRESHOLD: float = env_float("WHISPER_COMPRESSION_RATIO_THRESHOLD", "1.5")
WHISPER_REPETITION_PENALTY: float = env_float("WHISPER_REPETITION_PENALTY", "1.5")
WHISPER_VAD_MIN_SILENCE_MS: int = env_int("WHISPER_VAD_MIN_SILENCE_MS", "400")
WHISPER_VAD_SPEECH_PAD_MS: int = env_int("WHISPER_VAD_SPEECH_PAD_MS", "160")
WHISPER_VAD_THRESHOLD: float = env_float("WHISPER_VAD_THRESHOLD", "0.3")

WHISPER_NO_SPEECH_NOISE_SHIFT: float = env_float("WHISPER_NO_SPEECH_NOISE_SHIFT", "0.04")