FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS docbuilder
WORKDIR /docs

COPY mkdocs.yml .
COPY docs ./docs
COPY src ./src

RUN uv pip install --no-cache-dir -r ./docs/requirements.txt --system && \
    zensical build

FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    portaudio19-dev \
    gcc \
    libc-dev \
    linux-headers-amd64 \
    libsndfile1-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY src/requirements.txt .

ENV UV_NATIVE_TLS=1

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install torch torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/cu121

RUN --mount=type=cache,target=/root/.cache/uv \ 
    uv pip install --system -r requirements.txt

COPY src/ .
COPY --from=docbuilder /docs/site /src/docs
    
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080","--log-config", "/src/logging_config.yaml"]