---

services:
  cg_server_run:
    build:
      context: .
      dockerfile: Containerfile
      args:
        BUILD_DOCS: ${BUILD_DOCS:-true}
    container_name: CaptionGlassesServer
    ports:
      - "8080:8080"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - PHRASE_TIMEOUT=${PHRASE_TIMEOUT}
      - MAX_DURATION=${MAX_DURATION}
      - VAD_THRESHOLD=${VAD_THRESHOLD}
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    devices:
      - nvidia.com/gpu=${GPU_DEVICE:-0}